http:
  middlewares:
    ondemand-timeout-60:
      plugin:
        traefik-ondemand-plugin:
          names:
            - TRAEFIK_HACKATHON_whoami
          serviceUrl: http://ondemand:10000
          timeout: 60
    retry:
      retry:
        attempts: 10
        initialInterval: 1s

  services:
    whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80"

  routers:
    whoami:
      rule: PathPrefix(`/whoami`)
      entryPoints:
        - "http"
      middlewares:
        - ondemand-timeout-60
        - retry
      service: "whoami"
