http:
  middlewares:
    ondemand:
      plugin:
        dev:
          serviceUrl: http://ondemand:10000
          names:
            - TRAEFIK_HACKATHON_whoami
          timeout: 10
    retry:
      retry:
        attempts: 10
        initialInterval: 1s

  services:
    whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80"

  routers:
    whoami:
      rule: PathPrefix(`/whoami`)
      entryPoints:
        - "http"
      middlewares:
        - ondemand
        - retry
      service: "whoami"
